
version: 2

models:
  - name: int_orders__predqm
    columns:
      - name: dq_col
        tests:
          - check_not_null:
              primary_key: o_orderkey
              severity_level: warn
  - name: stg_orders

sources:
  - name: raw
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
    - name: orders